<?php
use Application\Infrastructure\Utils\Display;

$this->headTitle()->append(Display::formatString('MODELS'));
?>

<h1><?php echo Display::formatString($this->title);?></h1>
<?php foreach ($this->content as $category){

    ?>
    <a href="<?php echo $this->path; ?>/<?php echo $category['slug']; ?>">
        <?php if (array_key_exists('imagepath',$category)) {?>
            <img src="<?php echo $category['imagepath'];?>" /><br />
        <?php } ?>
        <?php echo Display::formatString($category['name']); ?><br />
    </a>
<?php } ?>

